---
title: Relaton specification -- Specific categories
description: Conventions specific to bibliographis categories in Relaton
---

[[specific-categories]]
== Specific categories of information resource

=== Electronic information resources

* Source: ISO 690, Clause 5.3

System requirements are modelled as a note, prefixed with "`System requirements`:".

NOTE: Detailed system requirements are
less commonly expressed now for software than they were in the 1990s and 2000s.

URLs should not be broken at the end of a line: that
is a rendering requirement, not an information modelling requirement.

As discussed in link:relatonspec-x01-bibtype[Categories of information resource],
where possible, a more specific category
should be used than "electronic resource",
which is properly a description of a medium and not a resource type; monographs and
journals are now routinely published online.

The specific type of electronic resource, if not covered by `bibitem/@type` (e.g.
"book", "dataset"), should be given as `medium/genre`.

====
Ubisoft. _Far Cry 5_ [computer game]. 2018. Viewed: 2018-05-10.
System requirements: CPU: Intel Core i5-2400 | AMD FX-6300 @ 3.5 GHz or better
(minimum); Intel Core i7-4770 @ 3.4 GHz | AMD Ryzen 5 1600 @ 3.2 GHz or equivalent (recommended).
RAM: 8 GB. OS: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only).
VIDEO CARD: NVIDIA GeForce GTX 670 | AMD R9 270 (2GB VRAM with Shader Model 5.0 or better) (minimum);
NVIDIA GeForce GTX 970 or AMD R9 290X (4GB VRAM with Shader Model 5.0 or better) (recommended).

[source,xml]
--
<bibitem type="software">
  <title>Far Cry 5</title>
  <date type="published"><on>2018</on></date>
  <date type="accessed"><on>2018-05-10</on></date>
  <contributor>
    <role type="author"/>
    <organization>
      <name>Ubisoft</name>
    </person>
  </organization>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Ubisoft</name>
    </organization>
  </contributor>
  <medium>
    <genre>computer game</genre>
  </medium>
  <note>System requirements: CPU: Intel Core i5-2400 | AMD FX-6300 @ 3.5 GHz or better
(minimum); Intel Core i7-4770 @ 3.4 GHz | AMD Ryzen 5 1600 @ 3.2 GHz or equivalent (recommended).
RAM: 8 GB. OS: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only).
VIDEO CARD: NVIDIA GeForce GTX 670 | AMD R9 270 (2GB VRAM with Shader Model 5.0 or better) (minimum);
NVIDIA GeForce GTX 970 or AMD R9 290X (4GB VRAM with Shader Model 5.0 or better) (recommended).</note>
</bibitem>
--
====

=== Cartographic material

* Source: ISO 690, Clause 5.4


The projection, prime meridian, orientation, and reference systems (such as
grids and navigational lattices) are given as notes.
The spectral characteristics of the sensor, details of the satellite systems,
and the amount of cloud cover are also given as notes.
Details of the creator's role are given in `bibitem/contributor/role`.


====
Berner, L.T., P.S.A. Beck, M.M. Loranty, H.D. Alexander, M.C. Mack, and S.J. Goetz.
_Siberian Boreal Forest Aboveground Biomass and Fire Scar Maps, Russia, 1969-2007_.
ORNL DAAC, Oak Ridge, Tennessee, USA. 2016. http://dx.doi.org/10.3334/ORNLDAAC/1321

[source,xml]
--
<bibitem type="map">
  <title>Siberian Boreal Forest Aboveground Biomass and Fire Scar Maps, Russia, 1969-2007</title>
  <date type="published"><on>2016</on></date>
  <docidentifier type="DOI">10.3334/ORNLDAAC/1321</docidentifier>
  <uri>https://daac.ornl.gov/VEGETATION/guides/Siberian_Biomass_Wildfire.html</uri>
  <contributor>
    <role type="author">
    <person><name><completeName>Berner, L.T.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">
    <person><name><completeName>Beck, P.S.A.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">
    <person><name><completeName>Loranty, H.D.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">
    <person><name><completeName>Mack, M.C.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">
    <person><name><completeName>Goetz, S.J.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Oak Ridge National Laboratory</name>
      <subdivision>Distributed Active Archive Center</subdivision>
      <abbreviation>ORNL DAAC</abbreviation>
    </organization>
  </contributor>
  <medium>
    <form>map</form>
    <size>col. 68 x 69 cm. fold. in envelope 30 x 24 cm.</size>
    <scale>1:62500</scale>
  </medium>
  <note>Type: Projected
Projection: Albers_Conic_Equal_Area
Geographic Coordinate Reference:  WGS 1984
Prime Meridian: Greenwich
Extent: North: 69.8980555555556 South: 64.4575 West: 155.931944444444 East: 166.474444444444</note>
<note>Satellites:
Biomass Mapping: WorldView-1 (WV-1), Landsat 5 TM
Fire Scar Mapping: Landsat 7 ETM+, Landsat 5 TM, Landsat 1–3 MSS</note>
  <place>Oak Ridge, Tennessee, USA</place>
</bibitem>
--
====


=== Films, videos and broadcasts

* Source: ISO 690, Clause 5.5


If a single contributor is to be singled out as the creator of a resource, they
are assigned the `bibitem/contributor/role@type` of "`author`".
Otherwise, if the
resource is treated as a collaborative effort, the various contributors should
be listed with `bibitem/contributor/role@type` of "`performer`", with their
contributions differentiated in the `bibitem/contributor/role`.

Programmes within a series have the series modelled as a `bibitem/series`.
The title of the series is modelled as `bibitem/series/title`, and the title
of the episode as `bibitem/title`. The transmitting organisation and channel
are modelled as a contributor of type "`distributor`".

If an audiovisual resource is a contained item, the `bibitem/extent` gives
its location within the host item; this is typically a timestamp for visual
material, and a timestamp or a track for audio material.

====
_The Death of Stalin_. Directed by Armando Iannucci. 2017.

[source,xml]
--
<bibitem type="film">
  <title>The Death of Stalin</title>
  <date type="published"><on>2017</on></date>
  <contributor>
    <role type="performer">Directed by</role>
    <person>
      <name>
        <surname>Iannucci</surname>
        <forename>Armando</forename>
      </name>
    </person>
  </contributor>
</bibitem>
--
====

====
Armando Iannucci. _The Death of Stalin_. 2017.

[source,xml]
--
<bibitem type="film">
  <title>The Death of Stalin</title>
  <date type="published"><on>2017</on></date>
  <contributor>
    <role type="author">Directed by</role>
    <person>
      <name>
        <surname>Iannucci</surname>
        <forename>Armando</forename>
      </name>
    </person>
  </contributor>
</bibitem>
--
====

====
_Columbo_, Season 7, Episode 5. The Conspirators. Teleplay by Howard Berk.
NBC. 1978-05-13.

[source,xml]
--
<bibitem type="audiovisual">
  <title>The Conspirators</title>
  <date type="transmitted"><on>1978-05-13</on></date>
  <contributor>
    <role type="performer">Teleplay by</role>
    <person>
      <name>
        <surname>Berk</surname>
        <forename>Howard</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="distributor"/>
    <organization>
      <name>NBC</name>
    </organization>
  </contributor>
  <series>
    <title>Columbo</title>
    <number>Season 7</number>
    <partnumber>Episode 5</partnumber>
  </series>
</bibitem>
--
====

=== Graphic Works

* Source: ISO 690, Clause 5.6


The fuller description of a contributors role under `bibitem/contributor/role`
allows for Latin role descriptions such as _pinxit_ and _sculpsit_.

====
_[Tent of Darius]_ C. Le Brun pinxit. S. Gribelin sculpsit.
[painting]. 1702. At: Musée du Louvre, Inv. 2896.

[source,xml]
--
<bibitem type="graphical work">
  <title>[Tent of Darius]</title>
  <date type="created"><on>1702</on></date>
  <contributor>
    <role type="author">pinxit</role>
    <person><name><completeName>C. Le Brun</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">sculpsit</role>
    <person><name><completeName>S. Gribelin</completeName></name></person>
  </contributor>
  <medium>
    <form>painting</form>
  </medium>
  <accessLocation>Musée du Louvre, Inv. 2896.</accessLocation>
</bibitem>
--
====

=== Music

* Source: ISO 690, Clause 5.7
* Serialisation: `bibitem/contributor/role`

Librettists and composers are both contributors of role type "author"; the role
of composer and librettist needs to be differentiated in the contributor
role for proper rendering.

The type "`music`" covers both music scores and music recordings, as is done
in ISO 690. The two are differentiated in `medium`; following
the practice in ISO 690, `medium/content` "notated music" is used
for music scores, while `medium/carrier` is used for recordings
(audio disc = CD, online resource). While it is possible to cite music in the
abstract, without referencing either a score or a recording (especially if the
score is not published), this is not
good practice, for the same reason that particular editions are required
for citation of textual works.

====
ADAMS, John Coolidge. _Nixon in China_. Libretto by Alice GOODMAN. 2004 [1987].
Vocal score. New York: Boosey & Hawkes.


[source,xml]
--
<bibitem type="music">
  <title>Nixon in China</title>
  <date type="created"><on>1987</on></date>
  <date type="published"><on>2004</on></date>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>John Coolidge ADAMS</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">libretto by</role>
    <person><name><completeName>Alice GOODMAN</completeName></name></person>
  </contributor>
  <contributor>
    <role type="publisher">
    <organization><name>Boosey &amp; Hawkes</name></organization>
  </contributor>
  <medium>
    <content>notated music</content>
    <genre>vocal score</genre>
  </medium>
  <place>New York</place>
</bibitem>
--
====

====
ADAMS, John Coolidge. _Nixon in China_. Libretto by Alice GOODMAN. 2009.
Marin Alsop (Conductor). Colorado Symphony Orchestra. [Audio CD].
3 CDs. Naxos.

[source,xml]
--
<bibitem type="music">
  <title>Nixon in China</title>
  <date type="created"><on>1987</on></date>
  <date type="published"><on>2004</on></date>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>John Coolidge ADAMS</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">libretto by</role>
    <person><name><completeName>Alice GOODMAN</completeName></name></person>
  </contributor>
  <contributor>
    <role type="performer">conductor</role>
    <person><name><completeName>Marin ALSOP</completeName></name></person>
  </contributor>
  <contributor>
    <role type="performer"/>
    <organization><name>Colorado Symphony Orchestra</name></organization>
  </contributor>
  <contributor>
    <role type="publisher">
    <organization><name>Naxos</name></organization>
  </contributor>
  <medium>
    <carrier>audio disc</carrier>
  </medium>
  <place>New York</place>
  <extent type="locality:CD">
    <referenceTo>3</referenceTo>
  </extent>
</bibitem>
--

====


=== Patents

* Source: ISO 690, Clause 5.8

Patents are encoded similarly to contributions within a serial
(ISO 690, Clause 5.2), with the series designation for the
patent preceded by the country name or code. The date of application
is encoded as a date of type "`issued`".


====
Green, Martin Andrew. _Artificial amorphous semiconductors and applications to solar cells_. Australia, [Patent] application number 2005238988. Appl: 2005-04-29.

[source,xml]
--
<bibitem type="patent">
  <title>Artificial amorphous semiconductors and applications to solar cells</title>
  <date type="issued"><on>2005-04-29</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <surname>Green</surname>
      <forename>Martin</forename>
      <forename>Andrew</forename>
    </person>
  </contributor>
  <series>
    <title>Australia, [Patent] application number</title>
    <number>2005238988</number>
  </series>
</bibitem>
--
====

=== Archival materials

* Source:  ISO 690, Clause 5.10

The fonds or collection of an archival item is modelled as a series.
The box and folder number is encoded as an access location. The reference code
is encoded as an identifier. The archive is encoded as a contributor
of type "distributor" (since the archive makes the resource available,
even if to a restricted public).

====
HICKS, H. D. _Correspondence from Henry Davies Hicks to the Annapolis County electorate_. [1956-10-24]. MS-2-511, Box 15, Folder 9. Henry Davies Hicks fonds. At: Dalhousie University Archives, Halifax, Nova Scotia, Canada.

[source,xml]
--
<bibitem type="archival">
  <title>Correspondence from Henry Davies Hicks to the Annapolis County electorate</title>
  <docidentifier type="reference code">MS-2-511</docidentifier>
  <date type="created">1956-10-24</date>
  <contributor>
    <role type="author"/>
    <person>
      <surname>Hicks</surname>
      <initials>H. D.</initials>
    </person>
  </contributor>
  <contributor>
    <role type="distributor">archive</role>
    <organization>
      <name>Dalhousie University Archives</name>
      <address>
        <city>Halifax</city>
        <state>Nova Scotia</state>
        <country>Canada</country>
      </address>
    </organization>
  </contributor>
  <series>
    <title>Henry Davies Hicks fonds</title>
  </series>
  <accessLocation>Box 15, Folder 9</accessLocation>
</bibitem>
--
====

=== Datasets

* Source:  ISO 690, Clause 5.11

The organisation publishing or producing the dataset is modelled as a publisher;
the organisation hosting the dataset in a repository is modelled as a distributor.
Data compilers, editors, investigators, and data managers are all modelled as editors.
Timestamps are modelled as extents; queries wherever possible should be entered as URIs.
Where that is not possible, the description of the necessary query to access the
required data subset should be presented as an `accessLocation`.

====
MILBERGER, S. (2002). _Evaluation of violence against women with physical disabilities in Michigan, 2000–2001_ (ICPSR version) [dataset] [data in several file formats and codebook/questionnaire in PDF]. Detroit: Wayne State University [producer]. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor

[source,xml]
--
<bibitem type="dataset">
  <title>Evaluation of violence against women with physical disabilities in Michigan, 2000–2001</title>
  <date type="created">2002</date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Milberger</surname>
        <initials>S.</initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher">producer</role>
    <organization>
      <name>Wayne State University</name>
      <address>
        <city>Detroit</city>
      </address>
    </organization>
  </contributor>
  <contributor>
    <role type="distributor">repository</role>
    <organization>
      <name>Inter-university Consortium for Political and Social Research</name>
      <address>
        <city>Ann Arbor</city>
        <state>MI</state>
      </address>
    </organization>
  </contributor>
  <version>
    <draft>ICPSR version</draft>
  </version>
  <note>data in several file formats and codebook/questionnaire in PDF</note>
</bibitem>
--
====

====
LEUPRECHT [et al.]. tas_CNRM-CERFACS-CNRM-CM5_RCP4.5_r1i1p1_CLMcom-CCLM4-8-17, [dataset]. Version 2. [Subset used: January to June 2014]. Vienna, Austria. CCCA Data Centre [distributor], 2016. Available from: https://hdl.handle.net/20.500.11756/93887ecf. [accessed 2017-06-28].

[source,xml]
--
<bibitem type="dataset">
  <title>tas_CNRM-CERFACS-CNRM-CM5_RCP4.5_r1i1p1_CLMcom-CCLM4-8-17</title>
  <docidentifier type="handle">https://hdl.handle.net/20.500.11756/93887ecf</docidentifier>
  <date type="created">2016</date>
  <date type="accessed">2017-06-28</date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Leuprecht</surname>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <completename>et al.</completename>
      </name>
    </person>
  </contributor>
    <contributor>
    <role type="distributor"/>
    <organization>
      <name>CCCA Data Centre</name>
    </organization>
  </contributor>
  <version><draft>Version 2</draft></version>
  <place>Vienna, Austria</place>
  <extent type="time">
    <referenceFrom>January 2014</referenceFrom>
    <referenceTo>June 2014</referenceTo>
  </extent>
</bibitem>
--
====

=== Social Media

* Source:  ISO 690, Clause 5.12

Social media items are typically items of `bibitem/@type` `webresource`,
although they may not always have an associated exposed URI (particularly
for social media accessed primarily via phone app, rather than web browser).
As with ISO 690, a distinction is made between items publicly available
(or at least, broadcast to a defined group of people), and one-on-one
text messages; the latter are conflated with voice and face-to-face communications
between individuals, and are cited as personal communications.

A person's real name may be related to the online identity assumed by the
author of the item, if both are known. The online identity is treated as a
pseudonym of the real life identity, and is serialised in the same way (link:relatonspec-x02-creator#variantnames[variantnames]).

The particular form of social media communication (e.g. blog post, forum post, tweet,
message) should be given through `medium/genre`.
At a lower priority, the service name or type should be encoded as `medium/form`, since it relates
to how the content is to be accessed by an intermediary app. (For example, a tweet
is not just accessed by a web browser, as a web resource; it is accessed and rendered
by a web browser in the context of Twitter.)



====
GATES, B. [BillGates]. (2013, February 26). #Polio is 99% eradicated. Join me & @FCBarcelona as we work to finish the job and #EndPolio. [Tweet]. Available from: https://twitter.com/BillGates/status/306195345845665792. [viewed 2016-07-06T12:30:15+02:00]. See also VIDEO: http://b-gat.es/X75Lvy.

[source,xml]
--
<bibitem type="social_media">
  <title>#Polio is 99% eradicated. Join me & @FCBarcelona as we work to finish the job and #EndPolio</title>
  <date type="published"><on>2013-02-26</on></date>
  <date type="accessed"><on>2016-07-06T12:30:15+02:00</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Gates</surname>
        <initial>B.</initial>
      </name>
      <variant type="username">
        <completename>BillGates</completename>
      </variant>
    </person>
  </contributor>
  <uri>https://twitter.com/BillGates/status/306195345845665792</uri>
  <medium>
    <form>Twitter</form>
    <genre>tweet</genre>
  </medium>
  <relation type="complements">
    <bibitem type="video">
       <uri>http://b-gat.es/X75Lvy</uri>
    </bibitem>
  </relation>
</bibitem>
--
====


