---
title: Additional Information
description: Additional information in Relaton
layout: model-doc
---

[[additional-info]]
== Additional general information

=== Classification

* Source: ISO 690, 4.11
* Serialisation: `bibitem/classification`

====
Giesler, Patricia. _Canada Remembers the Korean War_. Dewey 971.06 GIE 2003.
ISBN 0662674979. Charlottetown, P.E.I. : Veterans Affairs Canada. 2003.

[source,xml]
--
<bibitem type="book">
  <title>Canada Remembers the Korean War</title>
  <docidentifier type="ISBN">0662674979</docidentifier>
  <date type="published"><on>2003</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Giesler</surname>
        <forename>Patricia</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Veterans Affairs Canada</name>
    </organization>
  </contributor>
  <place>Charlottetown, P.E.I.</place>
  <classification type="Dewey">971.06 GIE 2003</classification>
</bibitem>
--

====

=== Keywords

* Source: N/A
* Serialisation: `bibitem/keyword`

====
[source,xml]
--
<keyword>Homo sapiens</keyword>

<keyword>
  <vocab>Homo sapiens</vocab>
  <vocabid type="wikidata" uri="https://www.wikidata.org/wiki/Q15978631">
    <code>Q15978631</code>
    <term>Homo sapiens</term>
  </vocabid>
  <vocabid type="National Biodiversity Network">
    <code>NHMSYS0000376773</code>
  </vocabid>
</keyword>

<keyword>
  <taxon>Hominidae</taxon>
  <taxon>Homininae</taxon>
  <taxon>Hominini</taxon>
  <taxon>Hominina</taxon>
  <taxon>Homo</taxon>
  <taxon>Homo sapiens</taxon>
  <vocabid type="wikispecies"><term>Homo_sapiens</term></vocabid>
</keyword>
--
====

=== Price and availability

* Source: ISO 690, 4.11
* Serialisation: `bibitem/price`, `bibitem/note`


Price is marked up as a distinct element, which contains the currency code, represented in ISO 4217.
The price should be treated as nominal, rather than capturing all possible pricings at a given time.

Availability information for a bibliographic item is treated
as a note. This also applies to the availability of an online resource,
and any access limitations, but not to licensing, which is encoded separately.

====
_Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling_.
Edited by Susan Gross Solomon. New York: St. Martin's Press, 1983. xiii, 179 pp.
$27.50. Available on request to the author.

[source,xml]
--
<bibitem type="book">
  <title>Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Solonom</surname>
        <forename>Susan</forename>
        <forename>Gross</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>St Martin's Press</name>
    </organization>
  </contributor>
  <note>Available on request to the author</note>
  <place>New York</place>
  <price currency="USD">27.50</price>
  <extent type="page">
    <referenceFrom>xiii</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>179</referenceFrom>
  </extent>
</bibitem>
--
====

=== License

* Source: ISO 690, 4.11
* Serialisation: `bibitem/license`, `bibitem/copyright`.

Where available, URIs should be used to identify licenses unambiguously.
If a URI is not available, a commonly accepted abbreviation or short name of
the license should be used.

.Indicating the BSD 2-clause license
====
[source,xml]
--
<license>BSD-2</license>
--
====

.Indicating the Creative Commons 2.0 license
====
[source,xml]
--
<license>https://creativecommons.org/licenses/by/2.0/</license>
--
====

Copyright is privileged with a separate element, incorporating copyright date
and owner, and scope. Scope is only used when multiple copyright statements apply to the
same document, indicating the scope of each copyright statement. It is preferable
if possible to use only one copyright statement per bibitem, and allot the other
copyright statements to distinct related bibitems (even if the scope involved is
as part of the publication, such as a chapter.)

.Copyright to a person
====
[source,xml]
--
<copyright>
  <from>1999</from>
  <owner><person><name><completename>Jack Frost</completename></person></owner>
</copyright>
--
====

.Multiple copyright statements
====
[source,xml]
--
<copyright>
  <from>1999</from>
  <owner><person><name><completename>Jack Frost</completename></person></owner>
  <scope>Original work</scope>
</copyright>
<copyright>
  <from>2002</from>
  <owner><person><name><completename>Johannes Raureif</completename></person></owner>
  <scope>Translation into German</scope>
</copyright>
--
====

.A copyright statement within a document relation
====
[source,xml]
--
<bibitem>
  ...
  <copyright>
    <from>1999</from>
    <owner><person><name><completename>Jack Frost</completename></person></owner>
  </copyright>
  ...
  <relation type="translatedFrom">
    <bibitem>
      ...
      <copyright>
        <from>2002</from>
        <owner><person><name><completename>Johannes Raureif</completename></person></owner>
      </copyright>
      ...
    </bibitem>
  </relation>
</bibitem>
--
====

=== Provenance and Authenticity

* Source: ISO 690, 4.11
* Serialisation: `bibitem/note`

Notes on bibliographical provenance, and checksums for digital resources,
are both given as bibliographic notes.

