---
title: Bibitem Type
description: Categories of information resource in Relaton
layout: model-docs
---

== Categories of information resource

* Source: ISO 690, Clause 5
* Serialisation: `bibitem@type`, `BibItemType`

While ISO 690 does not prescribe a list of possible bibliographic types,
there are categories specific to particular information resource categories
(ISO 690, Clause 5),
as well as rendering rules specific to information resource categories (e.g.
ISO 690, 5.5: series title appears before item title for
broadcasts).

For that reason, bibliographic items should indicate what bibliographic type
they belong to.

NOTE: The list of bibliographic types is a union of the types listed in ISO 690
and BibTeX. Master's Thesis and PhD Thesis from BibTeX are subsumed under `thesis`.

The supported types are:

* `article`
* `book`
* `booklet`
* `manual`
* `proceedings`
* `presentation`
* `thesis`
* `techreport`
* `standard`
* `map`
* `electronic resource`
* `audiovisual`
* `film`
* `video`
* `broadcast`
* `software`
* `graphic_work`
* `music`
* `patent`
* `inbook`
* `incollection`
* `inproceedings`
* `journal`
* `website`
* `webresource`
* `dataset`
* `archival`
* `social_media`
* `alert`
* `message`
* `conversation`
* `misc`
* `unpublished`

The list maintains a distinction between the following resources, all of which
are necessarily included in another resource:

`inbook`:: A typically untitled part of a book. May be a chapter (or section,
etc.) and/or a range of pages.
`incollection`:: A part of a book having its own title.
`inproceedings`:: An article in a conference proceedings.
`article`:: An article from a journal or magazine.

NOTE: The above distinction aligns with BibTeX usage.

The overloaded type "`electronic resource`" should be avoided where possible,
particularly if the resource corresponds closely to a paper bibliographic type,
such as `book` or `article`.

The following types have been added, as specialisations of "`electronic
resource`" with no print or physical counterpart:

`dataset`::
an electronic dataset, a collection of data that is not meant to be human-readable,
and which is typically only machine readable.

`webresource`::
a human-readable or consumable web resource,
a single item accessible online via a web browser,
which is not composed of components all of which can be accessed in the same
way. Includes media files, as well as individual web pages.

`website`::
a collection of web resources, presented under the same URL domain and by the same
(individual or corporate authorship).

`social_media`::
one or more resources within a collection that is typically collectively authored by member users.
Includes blog posts, forum posts, social media posts, tweets. Is usually a webresource,
but not always (e.g. blogs on WeChat are only accessible within the WeChat app.)

`software`::
computer executable code, not itself human-readable text (though it may generate such text).


The following types have been added, as specialisations of "electronic resource" with
a physical but not a print counterpart:

`alert`::
a single communication intended for multiple persons, and publicly accessible. May be
electronic (e.g. Facebook status update) or voice (e.g. evacuation alert), but is typically not print.

`message`::
a single communication intended for a restricted number of authorised persons (typically one).
May be electronic (e.g. Twitter direct message, email) or voice (e.g. a remark made to someone,
typically cited as "personal communication").

`conversation`::
an exchange of messages between two or more persons. May be electronic (e.g. web chat)
or voice (e.g. phone call).

Bibliographic types can overlap.

[example]
Social media can be treated as `webresource`, and `webresource`s are electronic
resources. A Facebook status update can be treated as an `alert`, or as
`social_media`.

However each bibliographic type is associated with a particular set of conventions
around citation, so classifying an item as belonging to a given bibliographic type determines how it will
be cited.

Following the classification of citations in ISO 690, `social_media` takes priority over other
types where it is applicable, particularly for publicly visible communications (such as status updates).

