---
title: Relaton model -- Creator
description: Categories of creator in Relaton
---

== Creator

=== General

* Source: ISO 690, Clause 4.1
* Serialisation: `bibitem/contributor`, `Person, Organization, Affiliation`

[[creator-selection]]
=== Selection

ISO 690, Clause 4.1 classifies the various possible roles a creator can have
with regard to a resource into six broad categories in order of priority,
with more refined classifications typically named for the creator. These
classifications
are retained in the model: `bibitem/contributor/role@type` provides the broad
category of role (author, performer, compiler, adaptor, publisher, distributor),
while `bibitem/contributor/role/description`
contains one or more specific descriptions of the role of the contributor.

The content of the `bibitem/contributor/role` element is optional, and contains
a more specific expression of the creator role. The description can be
strictly a noun, e.g. "librettist", or it can be a phrase, corresponding to how
it will be rendered in a citation ("libretto by"); the choice is at the discretion
of the bibliographer, and is determined by how the citation is expected to be rendered
(as rendering systems are unlikely to be sophisticated enough to convert the one
into the other.)

Whether subsidiary creators should be included in a bibliographic item, and
which creators should be included, is at the discretion of the bibliographer.

Exceptionally, "translator" is differentiated from the other "adaptor" roles,
because it is so different from other adaptor roles such
as engraver or photographer.

For derivative works, the creator and title of the original resource can be mentioned
as a bibliographic note (`bibitem/note`); however best practice is to treat the
original resource as a distinct related bibliographic item, related through the
`derivedFrom` relation (See link:../relations[Document Relations]). Likewise, different originators of different
editions should be modelled by modelling the editions as distinct related items,
each with its own distinct editor as contributor. (For example, the later edition given
as the main item, and the earlier edition related through a "updatedBy" relation.)

NOTE: Although both composer and librettist are included as authors under
ISO 690, Clause 4.1,
the two roles are clearly differentiated in ISO 690, Clause 5.7, with the
composer given priority over the librettist.

NOTE: Inventor and patentee are atypical of the "performer" roles,
and could arguably be regarded as author roles instead.

NOTE: Sponsoring organisations are conventionally included as distributors,
following practice in ISO 690.

====
Ramsey, J. K., & McGrew, W. C. (2005). Object play in great apes: Studies in nature and captivity.
In A. D. Pellegrini & P. K. Smith (Eds.), _The nature of play: Great apes and humans_
(pp. 89-112). New York, NY: Guilford Press.

[source,xml]
--
<bibitem type="incollection">
  <title>Object play in great apes: Studies in nature and captivity</title>
  <date type="published"><on>2005</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Ramsey</surname>
        <formatted-initials>J. K.</formatted-initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McGrew</surname>
        <formatted-initials>W. C.</formatted-initials>
      </name>
    </person>
  </contributor>
  <relation type="includedIn">
    <bibitem>
      <title>The nature of play: Great apes and humans</title>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Pellegrini</surname>
            <formatted-initials>A. D.</formatted-initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Smith</surname>
            <formatted-initials>P. K.</formatted-initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization>
          <name>Guilford Press</name>
        </organization>
      </contributor>
      <place>New York, NY</place>
    </bibitem>
  </relation>
  <extent type="page">
    <referenceFrom>89</referenceFrom>
    <referenceTo>112</referenceTo>
  </extent>
</bibitem>
--
====

====
Demosthenes. _Speeches 50-59_. Translated from the Greek by
Victor BERS. Austin: University of Texas Press, 2003.

[source,xml]
--
<bibitem type="book">
  <title>Speeches 50-59</title>
  <date type="published"><on>2003</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <completename>Demosthenes</completename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="translator"/>
    <person>
      <name>
        <surname>Bers</surname>
        <forename>Victor</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>University of Texas Press</name>
    </organization>
  </contributor>
  <language>en</language>
  <relation type="translatedFrom">
    <bibitem>
      <title>Speeches 50-59</title>
      <language>grc</language>
    </bibitem>
  </relation>
  <place>Austin</place>
</bibitem>
--
====

====
ROGET, Peter Mark. _Roget's Thesaurus_. Revised by
Susan M. LLOYD. Burnt Mill, Harlow, Essex: Longman Group Limited, 1982 [1852].

[source,xml]
--
<bibitem type="book">
  <title>Roget's Thesaurus</title>
  <date type="created"><on>1852</on></date>
  <date type="updated"><on>1982</on></date>
  <date type="published"><on>1982</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Roget</surname>
        <forename>Peter</forename>
        <forename>Mark</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="editor">revised</role>
    <person>
      <name>
        <surname>Lloyd</surname>
        <forename>Susan</forename>
        <forename>M.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Longman Group Limited</name>
    </organization>
  </contributor>
  <place>Burnt Mill, Harlow, Essex</place>
</bibitem>
--
====

====
WINSBACHER KNABENCHOR. All' Lust und Freud'. Frankfurt: Bellaphon, 1983.

[source,xml]
--
<bibitem type="music">
  <title>All' Lust und Freud'</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="performer"/>
    <organization>
      <name>Winsbacher Knabenchor</name>
    </organization>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completename>Gastoldi, Giovanni Giacomo</completename></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completename>Isaak, Heinrich</completename></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completename>Othmayr, Caspar</completename></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completename>Demantius, Christoph</completename></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bellaphon</name>
    </person>
  </organization>
  <medium>
    <carrier>audio disc</carrier>
  </medium>
  <place>Frankfurt</place>
</bibitem>
--
====

=== Personal names

Names may be modelled either broken up into their constituent components
(prefix, forename, initials, surname, addition), or as a complete name string.
The latter is useful if
(contrary to the recommendation of ISO 690, Clause 4.1)
language-specific conventions for ordering of name components are to be
observed; e.g. "`James CLARK, John COWAN, MURATA Makoto`".

If there are multiple contributors named in a role, all contributors are
expected to be represented in the bibliographic entry.
This reflects practice in electronic bibliographic tools, and renderers
may choose to truncate contributors with "`et al.`" beyond a certain cutoff point.
If this information is not available, a dummy contributor can be
named with "`et al.`" as their `completename`, but this is not preferred.

The `formatted-initials` component is used if all forenames are replaced by initials.
If only the middle name is replaced by an initial, it is still treated as a
forename.

Forenames are given an `initial` attribute if initials are to be assembled on a more granular basis.

====
BACH, J.S.

[source,xml]
--
<person>
  <name>
    <surname>Bach</surname>
    <formatted-initials>J. S.</formatted-initials>
  </name>
</person>
--
====

====
PICASSO, Pablo

[source,xml]
--
<person>
  <name>
    <surname>Picasso</surname>
    <forename initial="P">Pablo</forename>
  </name>
</person>
--
====

====
KING, Martin Luther, Jr., Rev.

[source,xml]
--
<person>
  <name>
    <prefix>Dr.</prefix>
    <surname>King</surname>
    <forename>Martin</forename>
    <forename>Luther</forename>
    <addition>Jr.</addition>
    <addition>Rev.</addition>
  </name>
</person>
--
====

====
KING, Martin Luther, Jr.

[source,xml]
--
<person>
  <name>
    <completename>KING, Martin Luther, Jr.</completename>
  </name>
</person>
--
====

====
STEWART, John H.

[source,xml]
--
<person>
  <name>
    <surname>Stewart</surname>
    <forename>John</forename>
    <forename>H.</forename>
  </name>
</person>
--
====

[[organisation]]
=== Organisations

The model caters for both full names and abbreviations of organisations.
Subordinate body names are modelled separately from the parent body name; the
choice of whether
to model parent + subordinate or a single name depends on the degree of
independence of the subordinate body, as outlined in ISO 690, Clause 4.1.

====
St. Thomas University [Florida].

[source,xml]
--
<organization>
  <name>St. Thomas University [Florida]</name>
</organization>
--
====

====
St. Thomas University [New Brunswick].

[source,xml]
--
<organization>
  <name>St. Thomas University [New Brunswick]</name>
</organization>
--
====

====
ACADEMY OF ATHENS. Research Centre for Modern Greek Dialects.

[source,xml]
--
<organization>
  <name>Academy of Athens</name>
  <subdivision>Research Centre for Modern Greek Dialects</subdivision>
</organization>
--
====

[[variantnames]]
=== Pseudonyms and Variant Names

Variant names, and assumed names, can both be modelled
as notes on names. However, for greater clarity, and for modelling
of the internal structure of the variant or assumed name,
a variant name can be modelled, with the same level of detail
as default names. The type of variant, or relation between the name
and variant, needs to be made explicit in that case.
For example `pseudonym`/`pseudonymOf` for literary pseudonyms,
or `username`/`usernameOf` for social media usernames.

Variant names can be applied to personal names,
organization names, and organization subdivision names.

====
TWAIN, Mark [pseud. of Samuel Langhorne CLEMENS]

[source,xml]
--
<person>
  <surname>Twain</surname>
  <forename>Mark</forename>
  <note>pseud. of Samuel Langhorne CLEMENS</note>
</person>
--

[source,xml]
--
<person>
  <surname>Twain</surname>
  <forename>Mark</forename>
  <variant type="pseudonymOf">
    <surname>Clemens</surname>
    <forename>Samuel</forename>
    <forename>Langhorne</forename>
  </variant>
  <variant type="transliteration">
    <surname language="el">Τουαίην</surname>
    <forename language="el">Μαρκ</forename>
  </variant>
</person>
--
====

=== Anonymous and Varii

Descriptors of authors, such as "`Anon`" or
"`Various Authors`", should be given as `completename`
elements. The model does not standardise the designations of
authors. As with pseudonyms, the real name of the creator if known can be
modelled as a note, or as a name variant.

====
Anon. _Sir Gawain and the Green Knight_. Edited by R. A. WALDRON. Evanston:
Northwestern University Press, 1970.

[source,xml]
--
<bibitem type="book">
  <title>Sir Gawain and the Green Knight</title>
  <date type="published"><on>1970</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completename>Anon</completename></name></person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person><name><completename>R. A. WALDRON</completename></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Northwestern University Press</name>
    </person>
  </organization>
  <place>Evanston</place>
</bibitem>
--
====

====
Anon [Thomas Robert MALTHUS]. _An Essay on the Principle of Population_. 1st edition.
London: J. Johnson, 1798.

[source,xml]
--
<bibitem type="book">
  <title>An Essay on the Principle of Population</title>
  <date type="published"><on>1798</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completename>Anon</completename></name></person>
    <variantname type="realname">
      <completename>Thomas Robert MALTHUS</completename>
    </variantname>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <person><name><completename>J. Johnson</completename></name></person>
  </contributor>
  <edition>1st edition</edition>
  <place>London</place>
</bibitem>
--
====

