---
title: Relaton model -- Medium
description: Categories of medium in Relaton
---

[[medium]]
== Medium

* Source: ISO 690, Clause 4.4, ISO 690, Clause 5.4
* Serialisation: `bibitem/medium`

ISO 690 differentiates between the content type of the item,
the media type (which includes file format for electronic media),
the carrier type, the size of the item (which can include duration,
and electronic file size, as well as physical medium size), and
for maps, the scale of the item. These are all
modelled as elements of the item medium; the media type or file format
is modelled as `medium/form`.

There is no fixed vocabulary modelled for any of the elements of `medium`
(although ISO 690 suggests closed Resource Description and Access (RDA)
vocabularies for `medium/content` and `medium/carrier`, and IANA Media Type
is best practice for `medium/form` for electronic resources. As ISO 690
allows, there may be instances where the medium descriptions need to be
discursive.

ISO 690 suggests specifying detailed information about the type of electronic
information resource (e.g. "`statistical dataset`"), which cannot be represented
in the type of bibliographic item (`bibitem/@type`), and is likely to be to specific
for the RDA triple of content, carrier and form. The `medium/genre` element is intended
to convey this kind of information, and can be used more generally as a well-recognised
subclass of bibliographic type or content.

Information about alternate formats should be modelled as related bibliographic
items (through the "instance" document relation), each with their own medium information.

The size and scale of the item (`medium/size`, `medium/scale`)
usually contains numerical information, but is modelled as a string,
given the complications of how size and scale can be described, particularly for
cartographic material.

====
Sigur Rós.
Untitled [Vaka]. In: _( )_ [compact disc]. Track 1.
Mosfellsbær: Sundlaugin, 2002.

[source,xml]
--
<bibitem type="music">
  <title>Untitled</title>
  <title type="unofficial">Vaka</title>
  <date type="published"><on>2002</on></date>
  <contributor>
    <role type="author">composer</role>
    <organization><name>Sigur Rós</name></organization>
  </contributor>
  <medium>
    <form>compact disc</form>
  </medium>
  <relation type="partOf">
    <bibitem>
      <title>( )</title>
      <contributor>
        <role type="author">composer</role>
        <organization><name>Sigur Rós</name></organization>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization><name>Sundlaugin</name></organization>
      </contributor>
      <place>Mosfellsbær, Iceland</place>
    </bibitem>
  </relation>
  <extent type="track">
    <referenceFrom>1</referenceFrom>
  </extent>
</bibitem>
--
====

====
Easterbrook, Don J. _Geologic Map of Western Whatcom County, Washington_.
Map. 1:62,500. col. 68 x 69 cm. fold. in envelope 30 x 24 cm.
Miscellaneous Investigations Series, map 1-854-B. Reston, VA: U.S. Geological Survey, 1976.

[source,xml]
--
<bibitem type="map">
  <title>Geologic Map of Western Whatcom County, Washington</title>
  <date type="published"><on>1976</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completename>Easterbrook, Don J.</completename></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization><name>U.S. Geological Survey</name></organization>
  </contributor>
  <medium>
    <form>map</form>
    <size>col. 68 x 69 cm. fold. in envelope 30 x 24 cm.</size>
    <scale>1:62500</scale>
  </medium>
  <series>
    <title>Miscellaneous Investigations Series</title>
    <number>map 1-854-B</number>
  </series>
  <place>Reston, VA</place>
</bibitem>
--
====

====
GATES, B. [BillGates]. (2013, February 26).
#Polio is 99% eradicated. Join me & @FCBarcelona as we work to finish the job and #EndPolio.
[Tweet]. Available from: https://twitter.com/BillGates/status/306195345845665792.
[viewed 2016-07-06T12:30:15+02:00]. See also VIDEO: http://b-gat.es/X75Lvy.

[source,xml]
--
<bibitem type="electronic resource">
  <title>#Polio is 99% eradicated. Join me & @FCBarcelona as we work to finish the job and #EndPolio</title>
  <date type="published"><on>2013-02-26</on></date>
  <date type="accessed"><on>2016-07-06T12:30:15+02:00</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Gates</surname>
        <initial>B.</initial>
      </name>
      <variant type="username">
        <completename>BillGates</completename>
      </variant>
    </person>
  </contributor>
  <uri>https://twitter.com/BillGates/status/306195345845665792</uri>
  <medium>
    <form>Twitter</form>
    <genre>tweet</genre>
  </medium>
  <relation type="hasComplement">
    <bibitem type="video">
       <uri>http://b-gat.es/X75Lvy</uri>
    </bibitem>
  </relation>
</bibitem>
--
====

