---
title: Relaton model -- Numeration and Pagination
description: Numeration and pagination in Relaton
---

[[numeration]]
== Numeration and pagination

* Source: ISO 690, 4.7
* Serialisation: `bibitem/extent`, `bibitem/size`

The bibliographic `size` of an item is the measure of how large it is, in terms
of measurements related to content (volumes, pages, data size, duration). It is
distinct from the physical size of the time as an object (e.g. height and breadth of a book,
page size such as octavo), which is captured under `bibitem/medium/size`.

The measures included in the bibliographic size are presented as a sequence of types
and values, which add up to give the size of the item: `bibitem/size/value/@type` and
`bibitem/size/value`. For example, a book with two page numerations is described
by giving both: "`lxii + 490 pages`". This would be presented as:

[source,xml]
--
<size>
  <value type="page">lxii</value>
  <value type="page">490</value>
</size>
--

Likewise, the convention of listing plates separately from pages (unnumbered pages,
of different, glossier material, used for full-page illustrations) would be indicated as:

[source,xml]
--
<size>
  <value type="page">114</value>
  <value type="plate">3</value>
</size>
--

corresponding to "`114pp + 3 plates`".

====
_Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling_. Edited by Susan Gross Solomon. New York: St. Martin's Press, 1983. xiii, 179 pp. $27.50.

[source,xml]
--
<bibitem type="book">
  <title>Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Solonom</surname>
        <forename>Susan</forename>
        <forename>Gross</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>St Martin's Press</name>
    </organization>
  </contributor>
  <note>$27.50</note>
  <place>New York</place>
  <series>
    <title>Nevada Bureau of Mines and Geology Bulletin</title>
    <number>88</number>
  </series>
  <size>
    <value type="page">xiii</value>
    <value type="page">179</value>
  </size>
</bibitem>
--
====

====
John H. Stewart, Edwin H. McKee, and Harold K. Stager.
_Geology and mineral deposits of Lander County, Nevada_.
Nevada Bureau of Mines and Geology Bulletin 88. 1977.
Reno: University of Nevada. [114 pp, 3 plates]

[source,xml]
--
<bibitem type="book">
  <title>Geology and mineral deposits of Lander County, Nevada</title>
  <date type="published"><on>1977</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Stewart</surname>
        <forename>John</forename>
        <forename>H.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McKee</surname>
        <forename>Edwin</forename>
        <forename>H.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Stager</surname>
        <forename>Harold</forename>
        <forename>K.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>University of Nevada</name>
    </organization>
  </contributor>
  <place>Reno</place>
  <series>
    <title>Nevada Bureau of Mines and Geology Bulletin</title>
    <number>88</number>
  </series>
  <size>
    <value type="page">114</value>
    <value type="plate">3</value>
  </size>
</bibitem>
--
====


The bibliographic size of an item is differentiated from its `extent`, the range of
bibliographic size components it occupies within an item. Extent is typically a
characteristic of contained items (link:../relations#host-item["host item"]),
e.g. a page range within a monograph or a journal for a journal article or book chapter
(so "`pp. 25-45`").

Components of an item are modelled under the `bibitem/extent` element as
one or more "localities"; these consist of a locality type
(`bibitem/extent@type`), a locality value (`bibitem/extent/referenceFrom`),
and optionally a locality range endpoint (`bibitem/extent/referenceTo`).
The locality type is a superset of the types of bibliographic size: an extent
typically involves volumes, pages, or timestamps, but can also extent to other
subdivisions of text, such as figures or appendices.

If a locality is labelled conventionally with a range, but is in fact a single
item (as often occurs with volumes and issues; e.g. issue 18–19 is in fact a
single issue), the label should be associated with
`bibitem/extent/referenceFrom` rather than being treated as a true range.
However the rendering of the item will typically not be any different.

A part of a contained item may be cited, and thus may have an extent applying to
the contained item as well as the host item. This has posed difficulty for
some citation schemes (e.g. citing a page within a journal article, which itself
covers a page range: "`Dedes, D. 1993. Ποίηματα του Μαυλανά Ρουμή [Poems by
Mevlana Rumi]. _Ta Istorika_ 10.18-19: 3-22. pp. 7-19`".) However, the model
copes with this by separating the extent of a citation (link:../citation[Citation Model])
from the extent of a bibliograhic item, and the extent of a contained item
from the extent of a host item. In this instance, "`pp. 7-19`" would be treated
normally as part of the citation, not part of the bibliographic item.

A hierarchical locality is expressed by repeating the extent element
with the different applicable locality types; these should be given in
hierarchical order. (So, for example, "`chapter 4, table 9`".)

Discontinuous ranges are modelled by repeating the extent element for the same locality type.

Extent includes the volume and issues of a journal, if the
item is an article in the journal.

====
Dedes, D. 1993. Ποίηματα του Μαυλανά Ρουμή [Poems by Mevlana Rumi]. _Ta Istorika_ 10.18-19: 3-22.

[source,xml]
--
<bibitem type="article">
  <title lang="en">Poems by Mevlana Rumi</title>
  <title type="original" lang="ell">Ποίηματα του Μαυλανά Ρουμή</title>
  <date type="published"><on>1993</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Dedes</surname>
        <forename>Dimitrios</forename>
      </name>
    </person>
  </contributor>
  <series>
    <title>Ta Istorika</title>
  </series>
  <extent type="volume">
    <referenceFrom>10</referenceFrom>
  </extent>
  <extent type="issue">
    <referenceFrom>18–19</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>3</referenceFrom>
    <referenceTo>22</referenceTo>
  </extent>
</bibitem>
--
====

====
Ramsey, J. K., & McGrew, W. C. (2005). Object play in great apes: Studies in nature and captivity.
In A. D. Pellegrini & P. K. Smith (Eds.), _The nature of play: Great apes and humans_
(pp. 89-112). [308pp]. New York, NY: Guilford Press.

[source,xml]
--
<bibitem type="incollection">
  <title>Object play in great apes: Studies in nature and captivity</title>
  <date type="published"><on>2005</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Ramsey</surname>
        <formatted-initials>J. K.</formatted-initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McGrew</surname>
        <formatted-initials>W. C.</formatted-initials>
      </name>
    </person>
  </contributor>
  <relation type="includedIn">
    <bibitem>
      <title>The nature of play: Great apes and humans</title>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Pellegrini</surname>
            <formatted-initials>A. D.</formatted-initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Smith</surname>
            <formatted-initials>P. K.</formatted-initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization>
          <name>Guilford Press</name>
        </organization>
      </contributor>
      <place>New York, NY</place>
      <extent type="page">
        <referenceTo>308</referenceTo>
      </extent>
    </bibitem>
  </relation>
  <extent type="page">
    <referenceFrom>89</referenceFrom>
    <referenceTo>112</referenceTo>
  </extent>
</bibitem>
--
====

====
Brown, P. L. (1999, September 5). Tiffany glass and other tales from the crypt.
_The New York Times_, pp. 1, 5.

[source,xml]
--
<bibitem type="article">
  <title>Tiffany glass and other tales from the crypt</title>
  <date type="published"><on>1999-09-05</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Brown</surname>
        <formatted-initials>P. L.</formatted-initials>
      </name>
    </person>
  </contributor>
  <series>
    <title>The New York Times</title>
  </series>
  <extent type="page">
    <referenceFrom>1</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>5</referenceFrom>
  </extent>
</bibitem>
--
====

