---
title: Citation guide for 3GPP standards
flavor: 3GPP
description: Cite 3GPP standards
layout: cite-doc
---

== Citing 3GPP standards

=== General

To cite a 3GPP standard in your document, use document identifiers as citation keys. All 3GPP identiiers start with `3GPP` prefix.

=== Types of 3GPP documents

* TR - Technical Report +
`3GPP TR 01.00:R98/7.1.0`
* TS - Technical Specification +
`3GPP TS 01.01:Ph1/3.0.0`

=== Specification number

* `00` - General information +
`3GPP TR 00.01U:UMTS/3.0.0`
* `01` - Requirements +
`3GPP TR 01.00:Ph2/0.0.0`
* `02` - Service aspects (stage 1) +
`3GPP TR 02.08:Ph1/0.1.0`
* `03` - Technical realization (stage 2) +
`3GPP TR 03.01U:UMTS/0.8.0`
* `04` - Signalling protocols (stage 3) - user equipment to network +
`3GPP TS 04.01:Ph1/3.0.1`
* `05` - GSM radio aspects +
`3GPP TR 05.01U:UMTS/2.0.0`
* `06` - CODECs +
`3GPP TR 06.01U:UMTS/3.0.0`
* `07` - Data +
`3GPP TS 07.01:Ph1/3.2.0`
* `08` - Signalling protocols (stage 3) - (RSS-CN) +
`3GPP TS 08.01:Ph1/3.0.1`
* `09` - Signalling protocols (stage 3) - (infra-fixed-network) +
`3GPP TR 09.01:Ph1/3.0.1`
* `10` - Programme management +
`3GPP TR 10.01:R97/0.0.2`
* `11` - Subscriber Identity Module +
`3GPP TR 11.15:R97/1.0.0`
* `12` - OAM&P and Charging +
`3GPP TR 12.01U:UMTS/3.0.0`
* `13` - Access requirements and test specifications +
`3GPP TS 13.01:Ph2/4.0.0`
* `21` - Requirements +
`3GPP TR 12.01U:UMTS/3.0.0`
* `22` - Service aspects +
`3GPP TR 22.07U:UMTS/3.0.0`
* `23` - Technical realization +
`3GPP TR 23.039:R99/1.0.0`
* `24` - Signalling protocols (stage 3) - user equipment to network +
`3GPP TR 24.801:Rel-8/0.0.0`
* `25` - UTRA radio aspects +
`3GPP TR 25.700:Rel-12/0.0.1`
* `26` - CODECs +
`3GPP TR 26.078:Rel-4/4.0.0`
* `27` - Data +
`3GPP TR 27.00U:UMTS/1.2.1`
* `28` - Signalling protocols (stage 3) - (RSS-CN) and OAM&P and Charging (overflow from 32-range) +
`3GPP TR 28.800:Rel-14/0.0.0`
* `29` - Signalling protocols (stage 3) - (infra-fixed-network) +
`3GPP TR 29.800:Rel-7/0.1.0`
* `30` - Programme management +
`3GPP TR 30.00U:UMTS/3.0.0`
* `31` - Subscriber Identity Module (SIM/USIM), IC Cards. Test specs. +
`3GPP TR 31.801:Rel-15/1.0.0`
* `32` - OAM&P and Charging +
`3GPP TR 32.01U:UMTS/1.0.0`
* `33` - Security aspects +
`3GPP TR 33.20U:UMTS/3.0.0`
* `34` - UE and (U)SIM test specifications +
`3GPP TR 34.901:R99/2.0.0`
* `35` - Security algorithms +
`3GPP TR 35.909:Rel-4/4.0.0`
* `36` - LTE (Evolved UTRA) and LTE-Advanced radio aspects +
`3GPP TR 36.276:Rel-16/0.0.1`
* `37` - Multiple radio access technology aspects +
`3GPP TR 37.716-00-00:Rel-16/0.0.1`
* `38` - Radio technology beyond LTE +
`3GPP TR 38.716-01-01:Rel-16/0.0.1`
* `41` - Requirements +
`3GPP TR 41.031:Rel-4/4.0.0`
* `42` - Service aspects (stage 1) +
`3GPP TS 42.009:Rel-4/4.0.0`
* `43` - Technical realization (stage 2) +
`3GPP TS 43.005:Rel-8/8.0.0`
* `44` - Signalling protocols (user equipment to network) +
`3GPP TS 44.001:Rel-4/4.0.0`
* `45` - GSM radio aspects +
`3GPP TS 45.001:Rel-4/4.0.0`
* `46` - CODECs +
`3GPP TS 46.001:Rel-4/4.0.0`
* `47` - Data +
* `48` - Signalling protocols (RSS-CN) +
`3GPP TS 48.008:Rel-4/4.6.0`
* `49` - Signalling protocols (infra-fixed-network) +
`3GPP TR 49.001:Rel-4/4.0.0`
* `50` - Programme management +
`3GPP TR 50.059:Rel-4/4.0.0`
* `51` - Subscriber Identity Module +
`3GPP TS 51.011:Rel-4/4.0.0`
* `52` - O&M +
`3GPP TS 52.008:Rel-6/0.1.2`
* `55` - Security algorithms +
`3GPP TR 55.919:R99/3.0.0`
